services:
    _defaults:
        autowire: true
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Provider\DataTypeProvider:
        tags:
            - { name: data_type_provider }
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\FieldType\JenkinsServerChoiceFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\FieldType\JenkinsJobChoiceFieldType:
        tags:
            - { name: field_type}
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Form\Type\JenkinsJobFormType:
        tags: [form.type]
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Provisioner\BuildProvisioner:
        tags:
          - { name: domainator.provisioner.build, priority: 40 }
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Provisioner\DestroyProvisioner:
        tags:
            - { name: domainator.provisioner.destroy, priority: 90 }
    DigipolisGent\Domainator9k\CiTypes\JenkinsBundle\Factory\ApiServiceFactory:
